version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A habit_tracker worker -l info
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

volumes:
  postgres_data:
  redis_data:
